# FTS LOCAL DOCKER DEVELOPMENT ENV
version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  fts:
    platform: linux/amd64
    entrypoint: python3 -m FreeTAKServer.controllers.services.FTS -DataPackageIP=0.0.0.0 -AutoStart=True
    build: .
    ports:
      - "8000:8080"
      - "8087:8087"
      - "8443:8443"
      - "9000:9000"
      - "19023:19023"
    
    environment:
      - FTS_DATABASE_TYPE=MySQL
      - FTS_DB_PATH=root:password@db:3306/db
      - FTS_DP_ADDRESS= $$(curl ifconfig.me)
      - FTS_EXCHECK_PATH=/opt/excheck
      - FTS_EXCHECK_CHECKLIST_PATH=/opt/excheck/checklist
      - FTS_EXCHECK_TEMPLATE_PATH=/opt/excheck/templates
      - FTS_CERTS_PATH=/opt/excheck/certs
    volumes:
      - ftsdata:/opt/FTSData:rw
      - ./excheck:/opt/excheck:rw
      - logvolume01:/var/log:rw
      - ${PWD}:/FreeTAKServer:rw
    depends_on:
      - db
  
  
  
volumes:
  ftsdata:
  logvolume01:
  my-db:
  #ftsexcheck:

